// Re-exports do schema completo — usado por Drizzle (drizzle.config.ts)
// e pelo client em src/lib/db/index.ts pra acessar tabelas e relations.

export * from './enums'
export * from './users'
export * from './produtos'
export * from './kits'
export * from './compradores'
export * from './empresas'
export * from './cores'
export * from './fios'
export * from './modelos'
export * from './tamanhos'
export * from './maquinas'
export * from './estacoes'
export * from './ordens'
export * from './contas-marketplace'
export * from './tarefas'
export * from './remessas'
export * from './de-para-full'
export * from './estoque'
export * from './eventos'
export * from './vendas'
export * from './orcamentos'
export * from './permissoes'
export * from './relations'
